### PR TITLE
Fix bsc#1221231

### PR DESCRIPTION
**Pull request by varkoly**
HANA-Firewall creates insufficient configuration.
Add Ports 4__INST_NUM__3 and 4__INST_NUM__7 to HANA internal system replication

### CODE REVIEW

**Review by angelabriel — CHANGES_REQUESTED** [review]
missing port 4__INST_NUM__3 but 4__INST_NUM__7 is available twice. Please fix.
And - do we have any SAP documentation stating these ports as valid?

**Comment by varkoly** [comment]
For port 3xx03 I've found indexserver https://help.sap.com/docs/SAP_HANA_PLATFORM/6b94445c94ae495c83a19646e7c3fd56/82cea8fe69604f3ab0d4624248b6e523.html?version=2.0.02&locale=en-US
For port 3xx07 xsengine
https://s3-eu-west-1.amazonaws.com/gxmedia.galileo-press.de/leseproben/5287/reading_sample_sap_press_sap_hana_2_administration.pdf
and
https://www.stechies.com/hana-services-ports-interview-questions-answer/

**Comment by angelabriel** [comment]
Thanks for the documentation links. And yes, the 3xx03 and 3xx07 ports are listed (looking at the HANA Administration Guide for 2.0SPS07). But the 4xx03 and 4xx07 are not listed. So the question still remains, if these ports are really supposed to be open. May be asking SAP for more information can be helpful as opening ports in a firewall may be a security risk.
Anyway - as the syntax of the fix is now ok, I will approve the PR. But clarifying the open question would be really appreciated.

**Review by angelabriel — APPROVED** [review]
Looks good, but open question remains.

**Comment by petervarkoly** [comment]
Now I've found the reason of 4<INSTNUMBER>NN ports: https://help.sap.com/viewer/6b94445c94ae495c83a19646e7c3fd56/1.0.12/en-US/d20e1a973df9462fa92149f29ee2c455.html

**Pull request merged**
